#include "catalog.h"
#include <algorithm>
#include <cmath>
#include <fstream>
#include <gtest/gtest.h>

// --- 2b. Catalog Tests ---
// These use the real Hipparcos catalog files generated by
// tools/generate_catalog.py. Path is relative to the build/ directory where
// ctest runs.

static const char *STAR_FILE = "../data/catalog_stars.bin";
static const char *PAIR_FILE = "../data/catalog_pairs.bin";

class CatalogTest : public ::testing::Test {
protected:
  void SetUp() override {
    // Check that catalog files exist
    std::ifstream fs(STAR_FILE);
    if (!fs.good()) {
      GTEST_SKIP() << "Catalog files not found — run generate_catalog.py first";
    }
    db = std::make_unique<StarDatabase>(STAR_FILE, PAIR_FILE);
  }

  std::unique_ptr<StarDatabase> db;
};

TEST_F(CatalogTest, GetStarKnown) {
  // HIP 32349 = Sirius, the brightest star
  // Its approximate ICRS unit vector (RA=101.29°, Dec=-16.72°)
  CatalogStar s = db->get_star(32349);
  EXPECT_EQ(s.hip_id, 32349);

  // Verify it's a valid unit vector (magnitude ≈ 1)
  double mag = std::sqrt(s.x * s.x + s.y * s.y + s.z * s.z);
  EXPECT_NEAR(mag, 1.0, 1e-6);

  // Sirius: RA ≈ 101.29°, Dec ≈ -16.72°
  // z = sin(Dec) should be negative
  EXPECT_LT(s.z, 0.0);
}

TEST_F(CatalogTest, GetStarThrows) {
  EXPECT_THROW(db->get_star(999999), std::runtime_error);
}

TEST_F(CatalogTest, FindPairsReturnsResults) {
  // Pick two bright stars close together (within the 25° catalog FoV limit).
  // HIP 36850 (Castor) and HIP 37826 (Pollux) are ~4.5° apart in Gemini.
  CatalogStar s1 = db->get_star(36850);
  CatalogStar s2 = db->get_star(37826);

  double cos_true = s1.x * s2.x + s1.y * s2.y + s1.z * s2.z;

  auto pairs = db->find_pairs(cos_true, 1e-4);
  EXPECT_GT(pairs.size(), 0u);

  // The exact pair should be in the results
  bool found = false;
  for (const auto &p : pairs) {
    if ((p.id1 == 36850 && p.id2 == 37826) ||
        (p.id1 == 37826 && p.id2 == 36850)) {
      found = true;
      break;
    }
  }
  EXPECT_TRUE(found) << "Expected Castor-Pollux pair not found";
}

TEST_F(CatalogTest, FindPairsEmptyOnZeroTolerance) {
  // cos_val = 0.12345 is unlikely to be an exact match for any pair
  auto pairs = db->find_pairs(0.12345, 0.0);
  EXPECT_EQ(pairs.size(), 0u);
}

TEST_F(CatalogTest, FindPartnersIncludesKnownPair) {
  // Querying Castor's partners at the true cos(Castor, Pollux) angle should
  // return Pollux (along with any other stars at that angular separation).
  CatalogStar castor = db->get_star(36850);
  CatalogStar pollux = db->get_star(37826);
  double cos_true =
      castor.x * pollux.x + castor.y * pollux.y + castor.z * pollux.z;

  auto partners = db->find_partners(36850, cos_true, 1e-4);
  EXPECT_GT(partners.size(), 0u);
  EXPECT_NE(std::find(partners.begin(), partners.end(), 37826), partners.end())
      << "Expected Pollux (HIP 37826) in Castor's partner list at the right "
         "cosine separation";
}

TEST_F(CatalogTest, FindPartnersUnknownHipReturnsEmpty) {
  auto partners = db->find_partners(999999, 0.5, 1e-4);
  EXPECT_EQ(partners.size(), 0u);
}

TEST_F(CatalogTest, FindPartnersRespectsTolerance) {
  // With a tight tolerance and a cos value unlikely to land on any real pair,
  // we should get no partners.
  auto partners = db->find_partners(36850, 0.12345, 1e-12);
  EXPECT_EQ(partners.size(), 0u);
}
