#include "catalog.h"
#include <algorithm>
#include <array>
#include <chrono>
#include <cmath>
#include <cstdint>
#include <fstream>
#include <gtest/gtest.h>
#include <random>
#include <set>
#include <tuple>
#include <vector>

// --- 2b. Catalog Tests ---
// These use the real Hipparcos catalog files generated by
// tools/generate_catalog.py. Path is relative to the build/ directory where
// ctest runs.

static const char *STAR_FILE = "../data/catalog_stars.bin";
static const char *PAIR_FILE = "../data/catalog_pairs.bin";
static const char *PATTERN_FILE_20 = "../data/catalog_patterns_20.bin";

class CatalogTest : public ::testing::Test {
protected:
  void SetUp() override {
    // Check that catalog files exist
    std::ifstream fs(STAR_FILE);
    if (!fs.good()) {
      GTEST_SKIP() << "Catalog files not found — run generate_catalog.py first";
    }
    db = std::make_unique<StarDatabase>(STAR_FILE, PAIR_FILE);
  }

  std::unique_ptr<StarDatabase> db;
};

namespace {

// C++ reimplementation of the canonical-order + key helper from
// tools/generate_catalog.py:canonical_order_and_key. Used by the pattern-hash
// tests to construct keys from observed unit vectors the same way the
// generator did from catalog unit vectors. Must stay byte-equivalent to the
// Python version; see kPatternCanonicalOrderDoc in catalog.h.
constexpr int kEdgePairs[6][2] = {
    {0, 1}, {0, 2}, {0, 3}, {1, 2}, {1, 3}, {2, 3},
};
constexpr int kQuantBits = 10;
constexpr int kQuantScale = (1 << kQuantBits) - 1;

uint64_t pattern_key_from_vectors(const double vecs[4][3], const int ids[4],
                                  int ordered_ids_out[4]) {
  // 6 angular distances.
  double dists[6];
  for (int e = 0; e < 6; ++e) {
    int i = kEdgePairs[e][0], j = kEdgePairs[e][1];
    double d = vecs[i][0] * vecs[j][0] + vecs[i][1] * vecs[j][1] +
               vecs[i][2] * vecs[j][2];
    if (d > 1.0)
      d = 1.0;
    if (d < -1.0)
      d = -1.0;
    dists[e] = std::acos(d);
  }
  // Sort edge indices ascending by (distance, pair-lex).
  std::array<int, 6> edge_order{0, 1, 2, 3, 4, 5};
  std::sort(edge_order.begin(), edge_order.end(), [&](int a, int b) {
    if (dists[a] != dists[b])
      return dists[a] < dists[b];
    if (kEdgePairs[a][0] != kEdgePairs[b][0])
      return kEdgePairs[a][0] < kEdgePairs[b][0];
    return kEdgePairs[a][1] < kEdgePairs[b][1];
  });
  // Per-star edge-rank signature.
  std::array<std::array<int, 3>, 4> sig{};
  std::array<int, 4> sig_n{0, 0, 0, 0};
  for (int rank = 0; rank < 6; ++rank) {
    int e = edge_order[rank];
    int i = kEdgePairs[e][0], j = kEdgePairs[e][1];
    sig[i][sig_n[i]++] = rank;
    sig[j][sig_n[j]++] = rank;
  }
  for (int s = 0; s < 4; ++s)
    std::sort(sig[s].begin(), sig[s].end());
  // Canonical permutation: sort 4 local indices ascending by (signature, id).
  std::array<int, 4> canonical{0, 1, 2, 3};
  std::sort(canonical.begin(), canonical.end(), [&](int a, int b) {
    for (int k = 0; k < 3; ++k)
      if (sig[a][k] != sig[b][k])
        return sig[a][k] < sig[b][k];
    return ids[a] < ids[b];
  });
  // 5 ratios from sorted-distance edges, quantize to 10 bits.
  double sorted_d[6];
  for (int k = 0; k < 6; ++k)
    sorted_d[k] = dists[edge_order[k]];
  double largest = sorted_d[5];
  uint64_t q[5];
  for (int k = 0; k < 5; ++k) {
    double r = sorted_d[k] / largest;
    long v = std::lround(r * kQuantScale);
    if (v < 0)
      v = 0;
    if (v > kQuantScale)
      v = kQuantScale;
    q[k] = static_cast<uint64_t>(v);
  }
  uint64_t key = (q[4] << 40) | (q[3] << 30) | (q[2] << 20) | (q[1] << 10) |
                 (q[0] << 0);
  for (int k = 0; k < 4; ++k)
    ordered_ids_out[k] = ids[canonical[k]];
  return key;
}

// Apply a rotation matrix to a 3-vector.
void rotate3(const double R[3][3], const double v[3], double out[3]) {
  out[0] = R[0][0] * v[0] + R[0][1] * v[1] + R[0][2] * v[2];
  out[1] = R[1][0] * v[0] + R[1][1] * v[1] + R[1][2] * v[2];
  out[2] = R[2][0] * v[0] + R[2][1] * v[1] + R[2][2] * v[2];
}

} // namespace

TEST_F(CatalogTest, GetStarKnown) {
  // HIP 32349 = Sirius, the brightest star
  // Its approximate ICRS unit vector (RA=101.29°, Dec=-16.72°)
  CatalogStar s = db->get_star(32349);
  EXPECT_EQ(s.hip_id, 32349);

  // Verify it's a valid unit vector (magnitude ≈ 1)
  double mag = std::sqrt(s.x * s.x + s.y * s.y + s.z * s.z);
  EXPECT_NEAR(mag, 1.0, 1e-6);

  // Sirius: RA ≈ 101.29°, Dec ≈ -16.72°
  // z = sin(Dec) should be negative
  EXPECT_LT(s.z, 0.0);
}

TEST_F(CatalogTest, GetStarThrows) {
  EXPECT_THROW(db->get_star(999999), std::runtime_error);
}

TEST_F(CatalogTest, FindPairsReturnsResults) {
  // Pick two bright stars close together (within the 25° catalog FoV limit).
  // HIP 36850 (Castor) and HIP 37826 (Pollux) are ~4.5° apart in Gemini.
  CatalogStar s1 = db->get_star(36850);
  CatalogStar s2 = db->get_star(37826);

  double cos_true = s1.x * s2.x + s1.y * s2.y + s1.z * s2.z;

  auto pairs = db->find_pairs(cos_true, 1e-4);
  EXPECT_GT(pairs.size(), 0u);

  // The exact pair should be in the results
  bool found = false;
  for (const auto &p : pairs) {
    if ((p.id1 == 36850 && p.id2 == 37826) ||
        (p.id1 == 37826 && p.id2 == 36850)) {
      found = true;
      break;
    }
  }
  EXPECT_TRUE(found) << "Expected Castor-Pollux pair not found";
}

TEST_F(CatalogTest, FindPairsEmptyOnZeroTolerance) {
  // cos_val = 0.12345 is unlikely to be an exact match for any pair
  auto pairs = db->find_pairs(0.12345, 0.0);
  EXPECT_EQ(pairs.size(), 0u);
}

TEST_F(CatalogTest, FindPartnersIncludesKnownPair) {
  // Querying Castor's partners at the true cos(Castor, Pollux) angle should
  // return Pollux (along with any other stars at that angular separation).
  CatalogStar castor = db->get_star(36850);
  CatalogStar pollux = db->get_star(37826);
  double cos_true =
      castor.x * pollux.x + castor.y * pollux.y + castor.z * pollux.z;

  auto partners = db->find_partners(36850, cos_true, 1e-4);
  EXPECT_GT(partners.size(), 0u);
  EXPECT_NE(std::find(partners.begin(), partners.end(), 37826), partners.end())
      << "Expected Pollux (HIP 37826) in Castor's partner list at the right "
         "cosine separation";
}

TEST_F(CatalogTest, FindPartnersUnknownHipReturnsEmpty) {
  auto partners = db->find_partners(999999, 0.5, 1e-4);
  EXPECT_EQ(partners.size(), 0u);
}

TEST_F(CatalogTest, FindPartnersRespectsTolerance) {
  // With a tight tolerance and a cos value unlikely to land on any real pair,
  // we should get no partners.
  auto partners = db->find_partners(36850, 0.12345, 1e-12);
  EXPECT_EQ(partners.size(), 0u);
}

// --- k-vector parity / edge tests ---

namespace {
// Canonicalise a vector of CatalogPair as sorted (cos_val, min_id, max_id).
std::vector<std::tuple<double, int, int>>
canonicalise(const std::vector<CatalogPair> &v) {
  std::vector<std::tuple<double, int, int>> out;
  out.reserve(v.size());
  for (const auto &p : v) {
    int a = std::min(p.id1, p.id2);
    int b = std::max(p.id1, p.id2);
    out.emplace_back(p.cos_val, a, b);
  }
  std::sort(out.begin(), out.end());
  return out;
}
} // namespace

TEST_F(CatalogTest, KVectorMatchesBinarySearch) {
  // 1000 random (cos_target, tol) probes. The two implementations must return
  // identical sorted result sets.
  std::mt19937 rng(0xC0FFEEu);
  std::uniform_real_distribution<double> cos_dist(-1.0, 1.0);
  std::uniform_real_distribution<double> log_tol_dist(std::log(1e-7),
                                                      std::log(1e-3));
  const int N_QUERIES = 1000;
  int nonempty = 0;
  for (int q = 0; q < N_QUERIES; ++q) {
    double cos_target = cos_dist(rng);
    double tol = std::exp(log_tol_dist(rng));
    auto a = db->find_pairs(cos_target, tol);
    auto b = db->find_pairs_kvec(cos_target, tol);
    auto ca = canonicalise(a);
    auto cb = canonicalise(b);
    ASSERT_EQ(ca, cb) << "Mismatch at query " << q
                      << " cos_target=" << cos_target << " tol=" << tol
                      << " sizes=" << a.size() << "/" << b.size();
    if (!a.empty())
      ++nonempty;
  }
  // Sanity: at least some queries hit the catalog (so we're not just trivially
  // matching empty sets).
  EXPECT_GT(nonempty, 0);
}

TEST_F(CatalogTest, KVectorEdgeCases) {
  // Closest pair (top of descending array): a tight query around the
  // catalog's largest cos_val.
  CatalogStar s1 = db->get_star(36850);
  CatalogStar s2 = db->get_star(37826);
  double cos_close = s1.x * s2.x + s1.y * s2.y + s1.z * s2.z;
  {
    auto a = canonicalise(db->find_pairs(cos_close, 1e-4));
    auto b = canonicalise(db->find_pairs_kvec(cos_close, 1e-4));
    EXPECT_EQ(a, b);
    EXPECT_FALSE(a.empty());
  }

  // Query at exactly the same cos_target with zero tolerance — must agree
  // (likely empty or a single exact hit).
  {
    auto a = canonicalise(db->find_pairs(cos_close, 0.0));
    auto b = canonicalise(db->find_pairs_kvec(cos_close, 0.0));
    EXPECT_EQ(a, b);
  }

  // Far above the catalog's y_max: pair max cos is ~cos(0) = 1, but no pair
  // is at cos=1 (no duplicate stars), and the catalog only spans angles
  // <= 25°, so cos values cluster in [cos(25°), 1). A query at cos=1.5 is
  // out of range; both implementations should agree (empty after filter).
  {
    auto a = canonicalise(db->find_pairs(1.5, 1e-3));
    auto b = canonicalise(db->find_pairs_kvec(1.5, 1e-3));
    EXPECT_EQ(a, b);
    EXPECT_TRUE(a.empty());
  }

  // Far below y_min: cos = -0.95 (angle > 162°) is way outside the 25° FoV
  // catalog. Both should return empty.
  {
    auto a = canonicalise(db->find_pairs(-0.95, 1e-3));
    auto b = canonicalise(db->find_pairs_kvec(-0.95, 1e-3));
    EXPECT_EQ(a, b);
    EXPECT_TRUE(a.empty());
  }

  // Query straddling the catalog's lower boundary (smallest cos in pairs):
  // huge tolerance should encompass everything; both should return all pairs.
  {
    auto a = db->find_pairs(0.5, 10.0); // tolerance way wider than catalog
    auto b = db->find_pairs_kvec(0.5, 10.0);
    EXPECT_EQ(a.size(), b.size());
  }

  // Extremely tight query around a known exact cos value: must include the
  // Castor-Pollux pair under both.
  {
    auto a = db->find_pairs(cos_close, 1e-12);
    auto b = db->find_pairs_kvec(cos_close, 1e-12);
    auto ca = canonicalise(a);
    auto cb = canonicalise(b);
    EXPECT_EQ(ca, cb);
  }
}

TEST_F(CatalogTest, KVectorSmokeTimingNotSlower) {
  // Time 10K queries on both implementations. The k-vector path should be
  // at least as fast as binary search; we assert <= 1.5x (generous bound to
  // avoid flakes on noisy CI hosts).
  std::mt19937 rng(42u);
  std::uniform_real_distribution<double> cos_dist(0.85, 1.0); // realistic
  std::uniform_real_distribution<double> log_tol_dist(std::log(1e-6),
                                                      std::log(1e-4));
  const int N = 10000;
  std::vector<double> cos_targets(N), tols(N);
  for (int i = 0; i < N; ++i) {
    cos_targets[i] = cos_dist(rng);
    tols[i] = std::exp(log_tol_dist(rng));
  }

  volatile size_t sink = 0;

  auto t0 = std::chrono::high_resolution_clock::now();
  for (int i = 0; i < N; ++i) {
    auto v = db->find_pairs(cos_targets[i], tols[i]);
    sink += v.size();
  }
  auto t1 = std::chrono::high_resolution_clock::now();
  for (int i = 0; i < N; ++i) {
    auto v = db->find_pairs_kvec(cos_targets[i], tols[i]);
    sink += v.size();
  }
  auto t2 = std::chrono::high_resolution_clock::now();

  auto dt_bin = std::chrono::duration_cast<std::chrono::microseconds>(t1 - t0)
                    .count();
  auto dt_kvec =
      std::chrono::duration_cast<std::chrono::microseconds>(t2 - t1).count();
  std::cout << "[timing] find_pairs:      " << dt_bin << " us\n";
  std::cout << "[timing] find_pairs_kvec: " << dt_kvec << " us\n";
  if (dt_kvec > 0)
    std::cout << "[timing] speedup x"
              << (static_cast<double>(dt_bin) / static_cast<double>(dt_kvec))
              << "\n";
  // Soft: kvec must not be more than 1.5x slower than binary search.
  EXPECT_LE(dt_kvec, dt_bin * 3 / 2 + 1000);
  (void)sink;
}

// --- Phase 3e.2: pattern-hash catalog tests ---

// Fixture that additionally loads the 20° pattern catalog. Skipped when the
// generated binary isn't present (e.g. on a fresh checkout before
// generate_catalog.py runs).
class PatternCatalogTest : public CatalogTest {
protected:
  void SetUp() override {
    CatalogTest::SetUp();
    if (IsSkipped())
      return;
    std::ifstream fs(PATTERN_FILE_20, std::ios::binary);
    if (!fs.good()) {
      GTEST_SKIP() << "Pattern catalog not found — run generate_catalog.py";
    }
    // Read header + a sample of keys directly from the file so individual
    // tests can probe known-good keys without poking at private members.
    int32_t hdr[5];
    fs.read(reinterpret_cast<char *>(hdr), sizeof(hdr));
    pattern_count_ = hdr[4];
    // Read all keys (8 bytes each, 870k × 8 = ~7 MB — negligible). Skip the
    // 16-byte hips field per record.
    sample_keys_.reserve(static_cast<size_t>(pattern_count_));
    for (int i = 0; i < pattern_count_; ++i) {
      uint64_t k;
      int32_t hips[4];
      fs.read(reinterpret_cast<char *>(&k), sizeof(k));
      fs.read(reinterpret_cast<char *>(hips), sizeof(hips));
      sample_keys_.push_back(k);
    }
    fs.close();

    db->load_pattern_catalog(PATTERN_FILE_20);
  }

  int pattern_count_ = 0;
  std::vector<uint64_t> sample_keys_;
};

TEST_F(PatternCatalogTest, PatternCatalogLoads) {
  EXPECT_TRUE(db->has_pattern_catalog());
  // 15544 stars × C(8, 3) = 56 patterns ≈ 870k patterns per bin.
  EXPECT_GT(pattern_count_, 100000)
      << "Expected > 100k patterns in the 20° bin, got " << pattern_count_;
  // Exact-key lookup on a real catalog key returns at least one entry.
  ASSERT_GT(sample_keys_.size(), 0u);
  auto hits = db->find_pattern(sample_keys_.front());
  EXPECT_GT(hits.size(), 0u);
  EXPECT_EQ(hits.front().key, sample_keys_.front());
}

TEST_F(PatternCatalogTest, PatternKeyOrderingIsConsistent) {
  // Pick 5 patterns directly from the catalog, project their stars through
  // a known rotation, recompute the key using the same C++ helper, and
  // verify find_pattern returns at least one entry whose HIPs are a
  // permutation of the input. Confirms the rotation-invariance + canonical
  // ordering convention round-trips.
  std::vector<StarPattern> sample;
  std::mt19937_64 rng(0xBADA55ULL);
  std::uniform_int_distribution<int> pick(0, pattern_count_ - 1);
  for (int tries = 0; tries < 200 && sample.size() < 5; ++tries) {
    int idx = pick(rng);
    auto hits = db->find_pattern(sample_keys_[idx]);
    for (const auto &p : hits) {
      try {
        for (int s = 0; s < 4; ++s)
          (void)db->get_star(p.hips[s]);
        sample.push_back(p);
        if (sample.size() >= 5)
          break;
      } catch (...) {
        // Skip patterns referencing unknown HIPs (shouldn't happen).
      }
    }
  }
  ASSERT_GE(sample.size(), 5u) << "Could not sample 5 patterns from catalog";

  // A non-trivial rotation: 30° about an arbitrary axis.
  const double ax = 0.4, ay = 0.6, az = 0.5;
  const double n = std::sqrt(ax * ax + ay * ay + az * az);
  const double ux = ax / n, uy = ay / n, uz = az / n;
  const double theta = 30.0 * M_PI / 180.0;
  const double c = std::cos(theta), s = std::sin(theta), C = 1.0 - c;
  const double R[3][3] = {
      {c + ux * ux * C, ux * uy * C - uz * s, ux * uz * C + uy * s},
      {uy * ux * C + uz * s, c + uy * uy * C, uy * uz * C - ux * s},
      {uz * ux * C - uy * s, uz * uy * C + ux * s, c + uz * uz * C},
  };

  for (const auto &p : sample) {
    double vecs[4][3];
    int ids[4];
    for (int i = 0; i < 4; ++i) {
      CatalogStar st = db->get_star(p.hips[i]);
      double v_in[3] = {st.x, st.y, st.z};
      rotate3(R, v_in, vecs[i]);
      ids[i] = p.hips[i];
    }
    int ordered[4];
    uint64_t key = pattern_key_from_vectors(vecs, ids, ordered);

    auto hits = db->find_pattern(key);
    ASSERT_FALSE(hits.empty())
        << "find_pattern(key) returned no entries for a catalog pattern";

    std::set<int> input_set{p.hips[0], p.hips[1], p.hips[2], p.hips[3]};
    bool found_perm = false;
    for (const auto &h : hits) {
      std::set<int> hit_set{h.hips[0], h.hips[1], h.hips[2], h.hips[3]};
      if (hit_set == input_set) {
        found_perm = true;
        break;
      }
    }
    EXPECT_TRUE(found_perm)
        << "No catalog entry at key 0x" << std::hex << key << std::dec
        << " has HIPs matching {" << p.hips[0] << "," << p.hips[1] << ","
        << p.hips[2] << "," << p.hips[3] << "}";
  }
}

TEST_F(PatternCatalogTest, PatternTolerantLookupFindsExactKey) {
  // For each of 20 random catalog keys, tolerant lookup must return at least
  // as many results as exact lookup, and every exact result must appear in
  // the tolerant result.
  std::mt19937_64 rng(0xC0FFEEULL);
  std::uniform_int_distribution<int> pick(0, pattern_count_ - 1);
  for (int trial = 0; trial < 20; ++trial) {
    uint64_t key = sample_keys_[pick(rng)];
    auto e = db->find_pattern(key);
    auto t = db->find_pattern_tolerant(key);
    ASSERT_FALSE(e.empty());
    EXPECT_GE(t.size(), e.size());
    for (const auto &ep : e) {
      bool present = false;
      for (const auto &tp : t) {
        if (tp.key == ep.key && tp.hips[0] == ep.hips[0] &&
            tp.hips[1] == ep.hips[1] && tp.hips[2] == ep.hips[2] &&
            tp.hips[3] == ep.hips[3]) {
          present = true;
          break;
        }
      }
      EXPECT_TRUE(present) << "exact-lookup hit missing from tolerant lookup";
    }
  }
}

TEST_F(PatternCatalogTest, PatternTolerantLookupCount) {
  // Sanity bound: tolerant probe should not return more than 300× the exact
  // count on real catalog keys.
  std::mt19937_64 rng(0xFADEDULL);
  std::uniform_int_distribution<int> pick(0, pattern_count_ - 1);
  for (int trial = 0; trial < 100; ++trial) {
    uint64_t key = sample_keys_[pick(rng)];
    auto e = db->find_pattern(key);
    auto t = db->find_pattern_tolerant(key);
    ASSERT_FALSE(e.empty());
    EXPECT_LE(t.size(), e.size() * 300u)
        << "tolerant probe exploded at key 0x" << std::hex << key
        << " (exact=" << std::dec << e.size() << ", tolerant=" << t.size()
        << ")";
  }
}
