#include "catalog.h"
#include <algorithm>
#include <chrono>
#include <cmath>
#include <fstream>
#include <gtest/gtest.h>
#include <random>
#include <tuple>
#include <vector>

// --- 2b. Catalog Tests ---
// These use the real Hipparcos catalog files generated by
// tools/generate_catalog.py. Path is relative to the build/ directory where
// ctest runs.

static const char *STAR_FILE = "../data/catalog_stars.bin";
static const char *PAIR_FILE = "../data/catalog_pairs.bin";

class CatalogTest : public ::testing::Test {
protected:
  void SetUp() override {
    // Check that catalog files exist
    std::ifstream fs(STAR_FILE);
    if (!fs.good()) {
      GTEST_SKIP() << "Catalog files not found — run generate_catalog.py first";
    }
    db = std::make_unique<StarDatabase>(STAR_FILE, PAIR_FILE);
  }

  std::unique_ptr<StarDatabase> db;
};

TEST_F(CatalogTest, GetStarKnown) {
  // HIP 32349 = Sirius, the brightest star
  // Its approximate ICRS unit vector (RA=101.29°, Dec=-16.72°)
  CatalogStar s = db->get_star(32349);
  EXPECT_EQ(s.hip_id, 32349);

  // Verify it's a valid unit vector (magnitude ≈ 1)
  double mag = std::sqrt(s.x * s.x + s.y * s.y + s.z * s.z);
  EXPECT_NEAR(mag, 1.0, 1e-6);

  // Sirius: RA ≈ 101.29°, Dec ≈ -16.72°
  // z = sin(Dec) should be negative
  EXPECT_LT(s.z, 0.0);
}

TEST_F(CatalogTest, GetStarThrows) {
  EXPECT_THROW(db->get_star(999999), std::runtime_error);
}

TEST_F(CatalogTest, FindPairsReturnsResults) {
  // Pick two bright stars close together (within the 25° catalog FoV limit).
  // HIP 36850 (Castor) and HIP 37826 (Pollux) are ~4.5° apart in Gemini.
  CatalogStar s1 = db->get_star(36850);
  CatalogStar s2 = db->get_star(37826);

  double cos_true = s1.x * s2.x + s1.y * s2.y + s1.z * s2.z;

  auto pairs = db->find_pairs(cos_true, 1e-4);
  EXPECT_GT(pairs.size(), 0u);

  // The exact pair should be in the results
  bool found = false;
  for (const auto &p : pairs) {
    if ((p.id1 == 36850 && p.id2 == 37826) ||
        (p.id1 == 37826 && p.id2 == 36850)) {
      found = true;
      break;
    }
  }
  EXPECT_TRUE(found) << "Expected Castor-Pollux pair not found";
}

TEST_F(CatalogTest, FindPairsEmptyOnZeroTolerance) {
  // cos_val = 0.12345 is unlikely to be an exact match for any pair
  auto pairs = db->find_pairs(0.12345, 0.0);
  EXPECT_EQ(pairs.size(), 0u);
}

TEST_F(CatalogTest, FindPartnersIncludesKnownPair) {
  // Querying Castor's partners at the true cos(Castor, Pollux) angle should
  // return Pollux (along with any other stars at that angular separation).
  CatalogStar castor = db->get_star(36850);
  CatalogStar pollux = db->get_star(37826);
  double cos_true =
      castor.x * pollux.x + castor.y * pollux.y + castor.z * pollux.z;

  auto partners = db->find_partners(36850, cos_true, 1e-4);
  EXPECT_GT(partners.size(), 0u);
  EXPECT_NE(std::find(partners.begin(), partners.end(), 37826), partners.end())
      << "Expected Pollux (HIP 37826) in Castor's partner list at the right "
         "cosine separation";
}

TEST_F(CatalogTest, FindPartnersUnknownHipReturnsEmpty) {
  auto partners = db->find_partners(999999, 0.5, 1e-4);
  EXPECT_EQ(partners.size(), 0u);
}

TEST_F(CatalogTest, FindPartnersRespectsTolerance) {
  // With a tight tolerance and a cos value unlikely to land on any real pair,
  // we should get no partners.
  auto partners = db->find_partners(36850, 0.12345, 1e-12);
  EXPECT_EQ(partners.size(), 0u);
}

// --- k-vector parity / edge tests ---

namespace {
// Canonicalise a vector of CatalogPair as sorted (cos_val, min_id, max_id).
std::vector<std::tuple<double, int, int>>
canonicalise(const std::vector<CatalogPair> &v) {
  std::vector<std::tuple<double, int, int>> out;
  out.reserve(v.size());
  for (const auto &p : v) {
    int a = std::min(p.id1, p.id2);
    int b = std::max(p.id1, p.id2);
    out.emplace_back(p.cos_val, a, b);
  }
  std::sort(out.begin(), out.end());
  return out;
}
} // namespace

TEST_F(CatalogTest, KVectorMatchesBinarySearch) {
  // 1000 random (cos_target, tol) probes. The two implementations must return
  // identical sorted result sets.
  std::mt19937 rng(0xC0FFEEu);
  std::uniform_real_distribution<double> cos_dist(-1.0, 1.0);
  std::uniform_real_distribution<double> log_tol_dist(std::log(1e-7),
                                                      std::log(1e-3));
  const int N_QUERIES = 1000;
  int nonempty = 0;
  for (int q = 0; q < N_QUERIES; ++q) {
    double cos_target = cos_dist(rng);
    double tol = std::exp(log_tol_dist(rng));
    auto a = db->find_pairs(cos_target, tol);
    auto b = db->find_pairs_kvec(cos_target, tol);
    auto ca = canonicalise(a);
    auto cb = canonicalise(b);
    ASSERT_EQ(ca, cb) << "Mismatch at query " << q
                      << " cos_target=" << cos_target << " tol=" << tol
                      << " sizes=" << a.size() << "/" << b.size();
    if (!a.empty())
      ++nonempty;
  }
  // Sanity: at least some queries hit the catalog (so we're not just trivially
  // matching empty sets).
  EXPECT_GT(nonempty, 0);
}

TEST_F(CatalogTest, KVectorEdgeCases) {
  // Closest pair (top of descending array): a tight query around the
  // catalog's largest cos_val.
  CatalogStar s1 = db->get_star(36850);
  CatalogStar s2 = db->get_star(37826);
  double cos_close = s1.x * s2.x + s1.y * s2.y + s1.z * s2.z;
  {
    auto a = canonicalise(db->find_pairs(cos_close, 1e-4));
    auto b = canonicalise(db->find_pairs_kvec(cos_close, 1e-4));
    EXPECT_EQ(a, b);
    EXPECT_FALSE(a.empty());
  }

  // Query at exactly the same cos_target with zero tolerance — must agree
  // (likely empty or a single exact hit).
  {
    auto a = canonicalise(db->find_pairs(cos_close, 0.0));
    auto b = canonicalise(db->find_pairs_kvec(cos_close, 0.0));
    EXPECT_EQ(a, b);
  }

  // Far above the catalog's y_max: pair max cos is ~cos(0) = 1, but no pair
  // is at cos=1 (no duplicate stars), and the catalog only spans angles
  // <= 25°, so cos values cluster in [cos(25°), 1). A query at cos=1.5 is
  // out of range; both implementations should agree (empty after filter).
  {
    auto a = canonicalise(db->find_pairs(1.5, 1e-3));
    auto b = canonicalise(db->find_pairs_kvec(1.5, 1e-3));
    EXPECT_EQ(a, b);
    EXPECT_TRUE(a.empty());
  }

  // Far below y_min: cos = -0.95 (angle > 162°) is way outside the 25° FoV
  // catalog. Both should return empty.
  {
    auto a = canonicalise(db->find_pairs(-0.95, 1e-3));
    auto b = canonicalise(db->find_pairs_kvec(-0.95, 1e-3));
    EXPECT_EQ(a, b);
    EXPECT_TRUE(a.empty());
  }

  // Query straddling the catalog's lower boundary (smallest cos in pairs):
  // huge tolerance should encompass everything; both should return all pairs.
  {
    auto a = db->find_pairs(0.5, 10.0); // tolerance way wider than catalog
    auto b = db->find_pairs_kvec(0.5, 10.0);
    EXPECT_EQ(a.size(), b.size());
  }

  // Extremely tight query around a known exact cos value: must include the
  // Castor-Pollux pair under both.
  {
    auto a = db->find_pairs(cos_close, 1e-12);
    auto b = db->find_pairs_kvec(cos_close, 1e-12);
    auto ca = canonicalise(a);
    auto cb = canonicalise(b);
    EXPECT_EQ(ca, cb);
  }
}

TEST_F(CatalogTest, KVectorSmokeTimingNotSlower) {
  // Time 10K queries on both implementations. The k-vector path should be
  // at least as fast as binary search; we assert <= 1.5x (generous bound to
  // avoid flakes on noisy CI hosts).
  std::mt19937 rng(42u);
  std::uniform_real_distribution<double> cos_dist(0.85, 1.0); // realistic
  std::uniform_real_distribution<double> log_tol_dist(std::log(1e-6),
                                                      std::log(1e-4));
  const int N = 10000;
  std::vector<double> cos_targets(N), tols(N);
  for (int i = 0; i < N; ++i) {
    cos_targets[i] = cos_dist(rng);
    tols[i] = std::exp(log_tol_dist(rng));
  }

  volatile size_t sink = 0;

  auto t0 = std::chrono::high_resolution_clock::now();
  for (int i = 0; i < N; ++i) {
    auto v = db->find_pairs(cos_targets[i], tols[i]);
    sink += v.size();
  }
  auto t1 = std::chrono::high_resolution_clock::now();
  for (int i = 0; i < N; ++i) {
    auto v = db->find_pairs_kvec(cos_targets[i], tols[i]);
    sink += v.size();
  }
  auto t2 = std::chrono::high_resolution_clock::now();

  auto dt_bin = std::chrono::duration_cast<std::chrono::microseconds>(t1 - t0)
                    .count();
  auto dt_kvec =
      std::chrono::duration_cast<std::chrono::microseconds>(t2 - t1).count();
  std::cout << "[timing] find_pairs:      " << dt_bin << " us\n";
  std::cout << "[timing] find_pairs_kvec: " << dt_kvec << " us\n";
  if (dt_kvec > 0)
    std::cout << "[timing] speedup x"
              << (static_cast<double>(dt_bin) / static_cast<double>(dt_kvec))
              << "\n";
  // Soft: kvec must not be more than 1.5x slower than binary search.
  EXPECT_LE(dt_kvec, dt_bin * 3 / 2 + 1000);
  (void)sink;
}
