#pragma once
#include <cstddef>
#include <cstdint>
#include <string>
#include <unordered_map>
#include <vector>

struct CatalogStar {
  int hip_id;
  double x, y, z;
};

struct CatalogPair {
  double cos_val;
  int id1, id2;
};

// --- Phase 3e.1/3e.2: 4-star pattern hash catalog ---
//
// One entry of the pattern-hash catalog: a 64-bit quantized geometric key
// and the four HIP ids of the stars that form the pattern, in canonical
// order (see kPatternCanonicalOrderDoc).
struct StarPattern {
  uint64_t key;
  int hips[4];
};

// Canonical-order convention used by the pattern generator
// (tools/generate_catalog.py / generate_pattern_catalog) and required of
// Wave 2 / any consumer that wants to map an observed centroid 4-tuple
// back to specific HIPs.
//
// Given the 4-star pattern:
//   1. Compute the 6 unordered pairwise angular distances.
//   2. Sort the 6 edges ascending by distance (ties broken by lex order on
//      the input-local star pair (i, j) with i < j).
//   3. For each of the 4 stars, define its "edge signature" as the sorted
//      3-tuple of ranks (in 0..5) of the 3 sorted edges it is incident to.
//   4. Sort the 4 input-local star indices ascending lexicographically by
//      (signature, input_id) where input_id is the HIP (catalog side) or
//      the centroid index (observer side). The resulting permutation is
//      the canonical order. hips[i] is the HIP of the i-th star in that
//      order.
//
// The convention is rotation-invariant (geometry-only) and reproduces the
// same position-by-position mapping whether you start from HIPs or from
// centroid indices, so the observer can recover the correct HIP→centroid
// assignment by simply pairing positions.
constexpr const char *kPatternCanonicalOrderDoc =
    "hips[i] is the i-th star in canonical order, where the 4 stars are "
    "sorted ascending by (edge_signature, input_id). edge_signature for a "
    "star is the sorted 3-tuple of ranks (in 0..5) of the 3 edges it is "
    "incident to, with the 6 edges sorted ascending by angular distance "
    "(lex tie-break on the input-local (i, j) pair). Geometry-only, so "
    "the same permutation comes out whether you feed HIPs or centroid "
    "indices.";

class StarDatabase {
public:
  StarDatabase(const std::string &star_file, const std::string &pair_file);
  ~StarDatabase();

  // Non-copyable / non-movable: holds raw mmap regions.
  StarDatabase(const StarDatabase &) = delete;
  StarDatabase &operator=(const StarDatabase &) = delete;
  StarDatabase(StarDatabase &&) = delete;
  StarDatabase &operator=(StarDatabase &&) = delete;

  // Find all catalog pairs within a tolerance around a cosine distance
  // (binary-search implementation, kept for parity tests).
  std::vector<CatalogPair> find_pairs(double cos_target,
                                      double cos_tolerance) const;

  // Same semantics as find_pairs, but uses Mortari's k-vector for O(1)
  // boundary lookup. Falls back to find_pairs if the k-vector index is not
  // loaded.
  std::vector<CatalogPair> find_pairs_kvec(double cos_target,
                                           double cos_tolerance) const;

  // Find all HIPs C such that cos(hip, C) is within tolerance of cos_target.
  // Used by pyramid-style identification to extend a seed (A, B) to a third
  // star without scanning the full pair list.
  std::vector<int> find_partners(int hip, double cos_target,
                                 double cos_tolerance) const;

  // Retrieve star by HIP ID
  CatalogStar get_star(int hip_id) const;

  // --- Phase 3e.2: pattern-hash catalog ---
  //
  // Load a pattern-hash catalog for one FOV bin (file generated by
  // tools/generate_catalog.py:generate_pattern_catalog). Throws on missing
  // file, bad magic, or short body. Does not replace the cosine-pair index;
  // existing identification continues to use find_pairs/find_partners.
  void load_pattern_catalog(const std::string &pattern_file);

  // Exact-key lookup. Returns all patterns whose key equals `key`. Internal
  // storage is sorted ascending by key, so this is a std::lower_bound /
  // upper_bound binary search → O(log P + hits).
  std::vector<StarPattern> find_pattern(uint64_t key) const;

  // ±1 quantization tolerance in each of the 5 packed 10-bit dimensions.
  // Probes up to 3^5 = 243 keys (skips probes whose perturbed value would
  // underflow below 0 or overflow above 1023). Returned vector is the union
  // of all hits across probes; not deduplicated (the same pattern can in
  // principle live in only one bucket, but the union is taken across
  // distinct perturbed keys, which yields disjoint results).
  std::vector<StarPattern> find_pattern_tolerant(uint64_t key) const;

  // True iff load_pattern_catalog() has been called successfully and the
  // loaded catalog contains at least one pattern.
  bool has_pattern_catalog() const { return patterns_count_ > 0; }

private:
  // --- mmap bookkeeping (Phase 3f.4) ---
  // A region of file bytes mapped into our address space. The destructor
  // munlocks (best-effort) and munmaps each region. Ordering of mappings_
  // doesn't matter; we just iterate at teardown.
  struct MmapRegion {
    void *ptr = nullptr;
    size_t size = 0;
  };
  std::vector<MmapRegion> mappings_;

  // mmap helper: opens `path`, mmaps the whole file PROT_READ MAP_PRIVATE,
  // madvise(RANDOM), best-effort mlock, prefaults every page, registers the
  // mapping in `mappings_`, and returns (ptr, size). Throws on open/stat/mmap
  // failure (those are fatal); mlock failure is logged and ignored.
  std::pair<const uint8_t *, size_t> mmap_file(const std::string &path);

  // star_map remains heap-allocated: file is small (435 KB), and the hash
  // table itself can't live in a mmap'd file.
  std::unordered_map<int, CatalogStar> star_map;

  // pairs is the mmap'd CatalogPair array (sorted descending by cos_val).
  // Non-owning: lifetime is tied to the corresponding MmapRegion. The header
  // is `int32 num_pairs` at the start of the file, so pairs_ptr_ points at
  // ptr + 4 in the pair-file mapping.
  const CatalogPair *pairs_ptr_ = nullptr;
  size_t pairs_count_ = 0;

  // Per-star index: hip -> sorted (cos_distance, partner_hip) entries.
  // Built once in the constructor from the mapped pair array. Memory: 2 *
  // |pairs| entries. Note that this index dwarfs the pair file itself in
  // RAM (~250 MB vs 99 MB), so Phase 3f.4's mmap win is on the *file read*,
  // not on overall RSS.
  std::unordered_map<int, std::vector<std::pair<double, int>>>
      per_star_partners;

  // Mortari k-vector index. `kvec_K_ptr_[i]` is the largest index j in the
  // descending pairs array such that pairs[j].cos_val >= y_min + i * dq.
  // Null if the index file was not present (find_pairs_kvec then falls back).
  const int32_t *kvec_K_ptr_ = nullptr;
  size_t kvec_K_count_ = 0; // == kvec_M + 1 when loaded
  double kvec_y_min = 0.0;
  double kvec_y_max = 0.0;
  double kvec_dq = 0.0;
  int kvec_M = 0;

  // Pattern catalog (Phase 3e.2). Sorted ascending by key for
  // std::lower_bound lookup. Null until load_pattern_catalog() is called.
  const StarPattern *patterns_ptr_ = nullptr;
  size_t patterns_count_ = 0;
  int pattern_fov_bin_deg_ = 0;
  int pattern_k_nearest_ = 0;
  int pattern_quant_bits_ = 0;
};
